package cesur.examen.common;

import lombok.Getter;
import lombok.extern.java.Log;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

/**
 * EXAMEN DE ACCESO A DATOS
 * Diciembre 2023
 *
 * Nombre del alumno: Alejandro Álvarez Mérida
 * Fecha: 11-12-2023
 *
 * No se permite escribir en consola desde las clases DAO, Service y Utils usando System.out.
 * En su lugar, usa log.info(), log.warning() y log.severe() para mostrar información interna
 * o para seguir la traza de ejecución.
 */

@Log
public class HibernateUtil {

    /**
     * SessionFactory is stored as a static final object accessible by all other classes
     * using getter (getter is autogenerated by lombok)
     *
     * Configuration data is retrieved from hibernate.cfg.xml located in resource folder.
     */
    @Getter
    private static SessionFactory sessionFactory;

    static{
        log.info("Loading Hibernate configuration...");
        try {
            Configuration configuration = new Configuration();

            configuration.setProperty("hibernate.connection.url", "jdbc:mysql://localhost:3306/examenad");
            configuration.setProperty("hibernate.connection.username", "root");
            configuration.setProperty("hibernate.connection.password", "04112003");
            configuration.setProperty("hibernate.connection.driver_class", "com.mysql.cj.jdbc.Driver");

            Configuration cfg = new Configuration();
            cfg.configure();
            sessionFactory = cfg.buildSessionFactory();
            log.info("SessionFactory creada con exito!");
        } catch (Exception ex) {
            log.severe("Error al crear SessionFactory()");
            ex.printStackTrace();
        }
    }

}
